### ISSUE TITLE
No new posts loaded

### ISSUE THREAD

**Issue by blueturtleai** [hachyderm/community#119]
I’m using the standard iOS app. I see often the message „see new posts“ at top. But when I tap on it, no new posts are loaded. This happens now since about 2 days.

**Comment by quintessence** [comment]
👋 Mod here - would you mind doing a little bit of troubleshooting with us so we can try to narrow down the cause? To start:

- Can you verify if you have the same issues seeing new posts in the web UI
- Can you verify if you have the same issues with a different iOS client, any of them is fine - just want to test if it's only the client or something else

Thank you!

**Comment by mitsuhiko** [comment]
I observe the same behavior and I'm assuming this is in line with the other effects that you can see form the infrastructure being overloaded. I'm also receiving random failures to load anything, server errors coming up or timeouts performing requests. Related issues are #121, #108, #117, #116 and others. Hachyderm is going up and down constantly and generally does not perform reliable at least during European hours when I try to use it.

**Comment by superchromix** [comment]
New posts from followed users on other instances (more than 4 hours old) are not appearing on my Hachyderm timeline, in Germany as of 20:22 GMT.  Same behavior with the web interface or using Toot! for IOS.

**Comment by blueturtleai** [comment]
Thanks for your reply. Today it didn’t happen until now, so it’s possible that it was connected to the general performance issues. If it occurs again, I will try a different client.

I will observe this the next few days. If it doesn’t happen again, I will close this issue.

**Comment by blueturtleai** [comment]
Now the problem occurs again, but I think now I understand what’s going on: it seems, that in fact new posts are added to the feed when I tap on „see new posts“. But as these posts are older than the top post, they are added below the top post so I didn’t see them. I guess this happens bcs the queues are emptied now.

As this seems to be connected to the performance issues, which are hopefully fixed now, I close this issue now.

**Comment by superchromix** [comment]
The problem is not fixed.

Posts from more than 21 hours ago, posted by followed users on other instances, do not show up when trying to view them from hachyderm.io.

**Comment by blueturtleai** [comment]
Okay. But as the problem I reported seems to be connected to the performance issues, I closed my issue.
