### ISSUE TITLE
Follow requests outside of hachyderm.io are awaiting approval

### ISSUE THREAD

**Issue by stevenkuhn** [hachyderm/community#147]
This may seem like a weird issue, but I've tried making follow requests to people outside of hachyderm.io and all of those are pending approval. But follow requests inside the instance itself went through fine. I hope the screenshot below helps explain what I'm seeing.

![image](https://user-images.githubusercontent.com/109609/205221268-ed6cfe65-49e7-4262-8d89-aee28ed6fac7.png)

Is there a queue or something for outside requests that needs to catch up? Or is it something that happens on a schedule?

Thank you so much for all the demanding work and effort you all have put into this. It's been amazing and I just want to also express my sincere thanks and gratitude! ❤️🙌

**Comment by sparky005** [comment]
I'm seeing this too. It seems like the follow does actually go through and I start seeing the user in my home timeline, but their profile says that it's waiting for the follow request. These are users that do not actually have locked accounts as well

**Comment by stevenkuhn** [comment]
You raise a good point, @sparky005. I just checked 3-4 different profiles above by going directly to each of their follower page on their instance. I am listed as a follower on each of them. So, like you said, it seems like the follow does go through. But for some unknown reason my following page doesn't update to reflect that.

**Comment by jensantarelli** [comment]
So I think I might have a related issue. I moved from another server last night and uploaded the CSV of the people I followed to my hachyderm.io account. A bunch of them have a greyed-out following icon and when I got to their profiles, it looks like I'm not following them. If I click to follow, their status changes but upon doing a hard-refresh in my browser, the status reverts. 

<img width="317" alt="Screenshot 2022-12-02 at 8 19 54 AM" src="https://user-images.githubusercontent.com/20958297/205327907-47c1884c-a42c-43ac-a327-a1174e16316f.png">

BTW, this doesn't seem to be based on what server _they_ are on. Some people from the same server will be greyed out and others won't be. Let me know if you need anymore info about what I'm seeing or if I should move this to a separate issue. Thanks a bunch! :)

**Comment by maxfragg** [comment]
I assume, this is actually the same issue as [this one](https://github.com/hachyderm/community/issues/148) - and yes, migrating and importing seams to create such strange inbetween stats between following and not following, including this "awaiting approval"

**Comment by stevenkuhn** [comment]
The issue I'm experiencing is not from migrating and importing a CSV, but instead from the typical follow request.

For example, I attempted to follow Framework by going to https://hachyderm.io/@frameworkcomputer@fosstodon.org and clicking "Follow". The button quickly changes over to "Unfollow." I went back to my following list and initially the Unfollow icon appeared. But when I refreshed the page again, the "Awaiting Approval" icon appeared instead. If I go directly to https://fosstodon.org/@frameworkcomputer/followers, I appear in that list. However, it still shows as "Awaiting Approval" on my following list.

I don't remember there being a delay in early November, but we were also on v3.5.3 then too.

**Comment by stevenkuhn** [comment]
That being said, three of the people I follow on a different instance now show as officially followed and no longer have the "Awaiting Approval" icon. Eleven are still stuck in that state. I don't know if all of them are protected accounts (I doubt Framework is, but it's possible), if this is simply a delay between instances, or if there is a real issue. I'll post again if I start seeing the others flip over as well.

**Comment by quintessence** [comment]
👋 Mod here

I was catching up on this thread. Based on timing, I wonder if the initial issue was due to our migration. Can y'all let me know if this is still ongoing or if it resolved? Thank you :)

**Comment by cbane** [comment]
It's still ongoing for me after the migration. I followed three accounts yesterday (sometime after 13:00 UTC), and all three of them are in this state (awaiting approval on hachyderm, but following on the remote server). My account is @cbane@hachyderm.io if you want to (and can) have a look.

**Comment by stevenkuhn** [comment]
> I was catching up on this thread. Based on timing, I wonder if the initial issue was due to our migration. Can y'all let me know if this is still ongoing or if it resolved? Thank you :)

It looks like this is something that takes a couple of days to resolve itself. A few hours ago, all but four were fixed. Now all of them are fine. 👍👍 I did unfollow and refollow Framework, so that one is now stuck at "awaiting approval." But my guess is that it will resolve itself in a day or two as well. 

I'm okay with closing this, but I understand keeping it open if others are still experiencing this issue.

**Comment by jensantarelli** [comment]
@quintessence I just did a hard-refresh in browser and the icons all seem to be reflecting the correct follow status now. Those people are also showing up in my home feed too, so I think this is resolved for me. Thanks! :)

**Comment by sparky005** [comment]
All the folks that I was having issues with yesterday are correctly showing up as followed. However, two people that I followed today are in that weird gray hourglass state, even though the follow has apparently gone through and I am already seeing their posts in my home timeline. My guess is that these ones will also become fixed over time, but that some lingering issue persists that's preventing the "follow confirmation" (for lack of a better term) from being immediately registered on hachyderm's side.

**Comment by quintessence** [comment]
Ok looks like all of these are resolved - if anyone experiences any more issues please open a new issue :) Closing for now :)
